# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Jade's Data Science Portfolio
author: Jade Natasha S. Ragot
logo: PortLogo.png

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: cache

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/JadeNatasha/Portfolio
  branch: main

html:
  use_issues_button: false
  use_repository_button: false

sphinx:
  config:
    html_theme_options:
      use_download_button: false
      use_fullscreen_button: false